image:
  repository: ghcr.io/mwinters/influx-mqtt-homeassistant
  tag: latest

env:
  INFLUX_URL: "http://influxdb.home-assistant.svc:8086"
  INFLUX_BUCKET: your-bucket
  INFLUX_TOKEN: tokentokentoken
  INFLUX_ORG: org
  MQTT_BROKER: "tcp://homeassistant.local:1883"
  MQTT_USERNAME: username
  MQTT_PASSWORD: password

resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
  requests:
    memory: "64Mi"
    cpu: "50m"